### ISSUE TITLE
'Find' return different results with same xpath

### ISSUE THREAD

**Issue by surpassly** [antchfx/htmlquery#12]
path := `//a|//img|//*[not(self::a)]/text()`
lines := htmlquery.Find(dom, path)
Every time I run the code, the sequence of lines is different, what's the problem?

**Comment by zhengchun** [comment]
hello, can you provide an example for test? is `for .. range = lines`  list values always in random order?

**Comment by surpassly** [comment]
> hello, can you provide an example for test? is `for .. range = lines` list values always in random order?

This is an example:
```go
content := `<p><img src="1.jpg"></p><p>1</p><p><img src="2.jpg"></p><p>2</p><p><img src="3.jpg"></p><p>3</p>`
dom, _ := htmlquery.Parse(strings.NewReader(content))
for i, l := range htmlquery.Find(dom, `//img|//*/text()`) {
    fmt.Println(i, l)
}
```
Expected output
```
0 &{0xc0000e <nil> <nil> <nil> <nil> 3 img img  [{ src 1.jpg}]}
1 &{0xc0000e <nil> <nil> <nil> <nil> 1  1  []}
2 &{0xc0000e <nil> <nil> <nil> <nil> 3 img img  [{ src 2.jpg}]}
3 &{0xc0000e <nil> <nil> <nil> <nil> 1  2  []}
4 &{0xc0000e <nil> <nil> <nil> <nil> 3 img img  [{ src 3.jpg}]}
5 &{0xc0000e <nil> <nil> <nil> <nil> 1  3  []}
```
In fact the first time I run the code, output is
```
0 &{0xc0000e8770 <nil> <nil> <nil> <nil> 3 img img  [{ src 3.jpg}]}
1 &{0xc0000e84d0 <nil> <nil> <nil> <nil> 1  1  []}
2 &{0xc0000e8690 <nil> <nil> <nil> <nil> 1  2  []}
3 &{0xc0000e8850 <nil> <nil> <nil> <nil> 1  3  []}
4 &{0xc0000e83f0 <nil> <nil> <nil> <nil> 3 img img  [{ src 1.jpg}]}
5 &{0xc0000e85b0 <nil> <nil> <nil> <nil> 3 img img  [{ src 2.jpg}]}
```
the second time
```
0 &{0xc0000e83f0 <nil> <nil> <nil> <nil> 3 img img  [{ src 1.jpg}]}
1 &{0xc0000e85b0 <nil> <nil> <nil> <nil> 3 img img  [{ src 2.jpg}]}
2 &{0xc0000e8770 <nil> <nil> <nil> <nil> 3 img img  [{ src 3.jpg}]}
3 &{0xc0000e84d0 <nil> <nil> <nil> <nil> 1  1  []}
4 &{0xc0000e8690 <nil> <nil> <nil> <nil> 1  2  []}
5 &{0xc0000e8850 <nil> <nil> <nil> <nil> 1  3  []}
```
Every time I run the code, the output is different, seems like it‘s parallel, how can I get the correct sequence?

**Comment by zhengchun** [comment]
At https://blog.golang.org/go-maps-in-action , **Iteration order** section said `When iterating over a map with a range loop, the iteration order is not specified and is not guaranteed to be the same from one iteration to the next. Since the release of Go 1.0, the runtime has randomized map iteration order. ` 

the package return node set not always sequence in its order, it random.

**Comment by surpassly** [comment]
Thank you, so is it possible to get the correct sequence in other way?

**Comment by zhengchun** [comment]
I think not other ways to get yet. I make this as new feature in the to do list.

**Comment by zhengchun** [comment]
or you can calculate each of nodes deep level and then sort. like this:

```go
for _,n:=range list{
    t:=n
    deep:=0
    for t.MoveToParent{
      deep++
    }
    fmt.Println(deep,n)
}
// sort by deep
```

**Comment by surpassly** [comment]
Thank you!

**Comment by zhengchun** [comment]
i found a problem, in https://github.com/antchfx/xpath/blob/ce1d48779e67a1ddfb380995fe532b2e0015919c/query.go#L732, if you change list in order by it sequence,the return may be like following:

because a `//img|//*/text()` will execute `//img` before and then `//*/text()`.

0 &{0xc0000e83f0 <nil> <nil> <nil> <nil> 3 img img  [{ src 1.jpg}]}
1 &{0xc0000e85b0 <nil> <nil> <nil> <nil> 3 img img  [{ src 2.jpg}]}
2 &{0xc0000e8770 <nil> <nil> <nil> <nil> 3 img img  [{ src 3.jpg}]}
3 &{0xc0000e84d0 <nil> <nil> <nil> <nil> 1  1  []}
4 &{0xc0000e8690 <nil> <nil> <nil> <nil> 1  2  []}
5 &{0xc0000e8850 <nil> <nil> <nil> <nil> 1  3  []}

**Comment by zhengchun** [comment]
looks you need custom iterator all html node and determine what is you need ,like `for n := n.FirstChild; n != nil; n = n.NextSibling {}`.

**Comment by surpassly** [comment]
> At https://blog.golang.org/go-maps-in-action , **Iteration order** section said `When iterating over a map with a range loop, the iteration order is not specified and is not guaranteed to be the same from one iteration to the next. Since the release of Go 1.0, the runtime has randomized map iteration order. `
> 
> the package return node set not always sequence in its order, it random.





> i found a problem, in https://github.com/antchfx/xpath/blob/ce1d48779e67a1ddfb380995fe532b2e0015919c/query.go#L732, if you change list in order by it sequence,the return may be like following:
> 
> because a `//img|//*/text()` will execute `//img` before and then `//*/text()`.
> 
> 0 &{0xc0000e83f0 3 img img [{ src 1.jpg}]}
> 1 &{0xc0000e85b0 3 img img [{ src 2.jpg}]}
> 2 &{0xc0000e8770 3 img img [{ src 3.jpg}]}
> 3 &{0xc0000e84d0 1 1 []}
> 4 &{0xc0000e8690 1 2 []}
> 5 &{0xc0000e8850 1 3 []}

But this can not explain output
```
0 &{0xc0000e8770 <nil> <nil> <nil> <nil> 3 img img  [{ src 3.jpg}]}
1 &{0xc0000e84d0 <nil> <nil> <nil> <nil> 1  1  []}
2 &{0xc0000e8690 <nil> <nil> <nil> <nil> 1  2  []}
3 &{0xc0000e8850 <nil> <nil> <nil> <nil> 1  3  []}
4 &{0xc0000e83f0 <nil> <nil> <nil> <nil> 3 img img  [{ src 1.jpg}]}
5 &{0xc0000e85b0 <nil> <nil> <nil> <nil> 3 img img  [{ src 2.jpg}]}`
```
Now I changed my original xpath
`//a|//img|//*[not(self::a)]/text()`
to
`//*[self::a or self::img or (not(self::a) and ./text())`
then I still have to do some work to extract text but the sequence is correct

maybe the operator '|' need to be improved?

**Comment by zhengchun** [comment]
yes, I has committed new code to fix `|`. https://github.com/antchfx/xpath/commit/41ad65c2d0156e76e1073182bb36a137fd3bf968
