### ISSUE TITLE
add built-in query object caching for reuse in the multiple queries with the same query string

### ISSUE THREAD

**Issue by zhengchun** [antchfx/htmlquery#16]
`htmlquery` provides new methods [QuerySelector](https://godoc.org/github.com/antchfx/htmlquery#QuerySelector) and [QuerySelectorAll](https://godoc.org/github.com/antchfx/htmlquery#QuerySelectorAll), We can use compiled query object to reuse and avoid recompile the XPath query expression, this will shorter query speed time and improve application performance.

**Comment by subsr97** [comment]
As I understand, you're suggesting to cache compiled XPath query expressions for use by `FindOne` and `Find` methods.

But wouldn't the overhead of maintaining a cache be greater than the overhead caused by recompiling XPath queries?

**Comment by zhengchun** [comment]
In fact, caching frequently used query objects can improve query performance. [groupcache](https://github.com/golang/groupcache), I just caching Top N objects which the most frequent query object.

**Comment by zhengchun** [comment]
https://github.com/antchfx/htmlquery/blob/master/query_test.go#L47

goos: windows
goarch: amd64
pkg: github.com/antchfx/htmlquery
BenchmarkSelectorCache-4                20000000                55.2 ns/op
BenchmarkDisableSelectorCache-4           500000              3162 ns/op
PASS

**Comment by zhengchun** [comment]
`# Add XPath selector object caching feature ` https://github.com/antchfx/htmlquery/commit/14e39058a8849d0f71c08084c93efa03fb2634fd
