### ISSUE TITLE
How can I get a attribute value?

### ISSUE THREAD

**Issue by jddggh** [antchfx/htmlquery#17]
xpath is like this: //div[@class='blog-single-foot']/span[@class='pull-left']/a/@href
but I can't get the right value of the href attribute,  I don't want to use  
xpath like: //div[@class='blog-single-foot']/span[@class='pull-left']/a
 and then do htmlquery.SelectAttr(a, "href"), I just want to get the attribute directly, can anyone tell me why?

**Comment by zhengchun** [comment]
yes, you can, `//div[@Class='blog-single-foot']/span[@Class='pull-left']/a/@href` will return `@href` value.
```
node:=htmlquery.FindOne(doc,`//div[@Class='blog-single-foot']/span[@Class='pull-left']/a/@href`)
fmt.Println(htmlquery.InnerText(node))
```

**Comment by jddggh** [comment]
Thanks a lot, worked it out.

**Comment by popstk** [comment]
Hi，I met  the same issue.

``` go
package main

import (
	"fmt"
	"github.com/antchfx/xquery/html"
	"strings"
)

func main() {
	const text = `<dd><a href="/path/to/something.html">this is text!</a></dd>`
	doc, _ := htmlquery.Parse(strings.NewReader(text))
	node := htmlquery.FindOne(doc, `.//a/@href`)
	fmt.Println(htmlquery.InnerText(node))          // output: this is text!
	fmt.Println(htmlquery.SelectAttr(node, "href")) // output: /path/to/something.html
}
```

I can not get `href` attribute value by InnerText method.

**Comment by zhengchun** [comment]
`xquery` project was out, you should visit [htmlquery](https://github.com/antchfx/htmlquery).
