### ISSUE TITLE
Code example issue on README

### ISSUE THREAD

**Issue by otokunaga2** [antchfx/htmlquery#28]
Hi!
Thank you for excellent OSS.

I would like to try this library for my personal project.

However, when I tried to use this library along with README, 
the following example seemed not working in my environment.
So could you share the correct information?

my environment info is as follows
- Golang: go version go1.14.2 linux/amd64
- WSL: Ubuntu 18.04 LTS

```
//not worked
list := range htmlquery.Find(doc, "//a/@href")	
for n := range list{
	fmt.Println(htmlquery.InnerText(n)) // output @href value without A element.
}
//=> # command-line-arguments
//./main.go:16:34: cannot use n (type int) as type *html.Node in argument to htmlquery.InnerText

//worked
list := htmlquery.Find(doc, "//a@href")
for _, val := range list{
	fmt.Println(htmlquery.InnerText(val))
}
//=>More information...
```

**Comment by zhengchun** [comment]
Sorry, the example about `//a/@href` is wrong in the README. I will fix it. Thanks for feedback.

```
list := range htmlquery.Find(doc, "//a/@href")	
for _, node := range list{
	fmt.Println(htmlquery.InnerText(n)) 
}
```
