### ISSUE TITLE
[Runtime error] - invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by imthaghost** [antchfx/htmlquery#29]
![Screen Shot 2020-05-07 at 12 48 04 PM](https://user-images.githubusercontent.com/46610773/81338285-372aca00-9061-11ea-8276-6a960c87db70.png)

### How to replicate

```golang

XPath := "//*[@id=\"market-summary\"]/div[2]/div/div[1]/div[1]"

doc, err := htmlquery.LoadURL("https://stockx.com/air-jordan-1-retro-high-off-white-university-blue")
if err != nil {
panic(err)
}

s2 := htmlquery.FindOne(doc, XPath)

p := string(htmlquery.InnerText(s2))

return p
```

**Comment by zhengchun** [comment]
I tested and can works on the latest version of `htmlquery`. Update the `htmlquery` dependency package [xpath](https://github.com/antchfx/xpath/releases) to the latest version `1.1.6`
