### ISSUE TITLE
i/o timeout

### ISSUE THREAD

**Issue by 9kill** [antchfx/htmlquery#34]
go get github.com/antchfx/htmlquery

package golang.org/x/text/encoding: unrecognized import path "golang.org/x/text/encoding" (https fetch: Get https://golang.org/x/text/encoding?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

**Comment by zhengchun** [comment]
Looks that your request was been banned by your firewall when accessing `golang.org`. Make sure you can access `golang.org` on your browser.
