### ISSUE TITLE
Add configurable timeout to LoadURL

### ISSUE THREAD

**Issue by cnp96** [antchfx/htmlquery#36]
The `LoadURL` method should have a timeout parameter to avoid indefinite load time.
Optionally, it could also accept any other client parameters.

```go

func LoadURL(url string, clientOpts ...*http.Client) (*html.Node, error) {

}
```

**Comment by zhengchun** [comment]
Hello, @cnp96 , Thanks for your feedback.

No any plan to change or add more feature for `LoadURL` method. You can implements your http client to load html document and then call `Parse(reader)`.
