### ISSUE TITLE
Access inner text from node with other elements around

### ISSUE THREAD

**Issue by scharph** [antchfx/htmlquery#48]
I want to access the inner text " bar" from the node '\<code\>' which also has some '\<span\>' elements inside

```html
<html>
  <body>
    <pre>
        <code>
            <span>foo</span>
            <span>:</span> bar <!-- <<<< target -->
            <span>;</span>
        </code>
    </pre>
  </body>
</html>
```

```go
doc, err := htmlquery.LoadDoc(file)
if err != nil {
    return err
}
node := htmlquery.FindOne(doc, "html/body/pre/code")

fmt.Println(htmlquery.InnerText(node))
```

Actual result: "foo: bar;"
Expected: "bar"

For some reason the span's inner texts are also included.. how can I prevent this?

Tried it with this path tester [extendsclass.com/xpath-tester](https://extendsclass.com/xpath-tester.html) with the query _"//body/pre/code/text()"_ and it returns the expected value

Any ideas?

**Comment by zhengchun** [comment]
`htmlquery.InnerText` will output target element node all inner text including its child nodes.

Try change XPath to `html/body/pre/code/span[2]/following-sibling::text()`

Another way is using `//pre/code/text()` get all text node and then concat it.

```go
list := htmlquery.Find(doc, "//pre/code/text()")
for _, node := range list {
	fmt.Println(strings.TrimSpace(htmlquery.InnerText(node)))
}
```

**Comment by scharph** [comment]
Thank you .. work as expected 👍
