### ISSUE TITLE
`replace()` on a query doesn't seem to work

### ISSUE THREAD

**Issue by alecthomas** [antchfx/htmlquery#51]
```go
package main

import (
	"fmt"
	"strings"

	"github.com/antchfx/htmlquery"
)

func main() {
	s := `<html><a href="https://github.com/cashapp/hermit-build/releases/download/go-tools/stringer-v0.1.12-darwin-amd64.bz2">foo</a></html>`
	doc, err := htmlquery.Parse(strings.NewReader(s))
	if err != nil {
		panic(err)
	}
	nodes, err := htmlquery.QueryAll(doc, `replace((//a[contains(@href, '/stringer-')])/@href, '^.*/stringer-v([^-]*)-.*$', '$1')`)
	if err != nil {
		panic(err)
	}
	for _, node := range nodes {
		fmt.Println(htmlquery.OutputHTML(node, false))
	}
}
```

On playground: https://go.dev/play/p/jxU6UgH0DnK
The same content+query works fine on https://www.freeformatter.com/xpath-tester.html

The above example without `replace()` works fine: https://go.dev/play/p/N22KULbkgRu

**Comment by zhengchun** [comment]
There are two problem.

1. `replace()` not supportd the regular syntax.
2. `replace()` as a function and return a value with string type, you should call [`xpath.Evaluate(...)`](https://pkg.go.dev/github.com/antchfx/xpath#Expr.Evaluate), the `htmlquery.QueryAll()` always return a set of node.

```go
expr, err := xpath.Compile(`replace((//a[contains(@href, '/stringer-')])/@href, '^.*/stringer-v([^-]*)-.*$', '$1')`)
if err != nil {
	panic(err)
}
v := expr.Evaluate(htmlquery.CreateXPathNavigator(doc))
fmt.Println(v.(string))
```

**Comment by alecthomas** [comment]
Thank you for the pointers, I've switched to using `substring-after` and `substring-before`. BTW it [looks like](https://www.w3.org/TR/xpath-functions-31/#func-replace) replace should support regex?

**Comment by alecthomas** [comment]
Thanks for a great set of libraries BTW, really nicely done.
