### ISSUE TITLE
go: github.com/antchfx/htmlquery: invalid github.com import path "github.com/antchfx"

### ISSUE THREAD

**Issue by sputnick-dev** [antchfx/htmlquery#57]
When I run

    go get github.com/antchfx/htmlquery

I get

    go: github.com/antchfx/htmlquery: invalid github.com import path "github.com/antchfx"

go.mod:

    module github.com/antchfx/htmlquery

    go 1.18

**Comment by zhengchun** [comment]
It works for me.

> go get -v github.com/antchfx/htmlquery

```
go get: added github.com/antchfx/htmlquery v1.2.6
go get: added github.com/antchfx/xpath v1.2.2
go get: added github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
go get: added golang.org/x/net v0.5.0
go get: added golang.org/x/text v0.6.0
```

**Comment by zhengchun** [comment]
I guess you should change your module name `module github.com/antchfx/htmlquery` to the another name. It may conflict with `htmlquery`

**Comment by sputnick-dev** [comment]
Oops, sorry, yes
