### ISSUE TITLE
panic: not yet support this function lower-case()

### ISSUE THREAD

**Issue by zhangguanzhang** [antchfx/htmlquery#64]
panic: not yet support this function lower-case()

**Comment by zhengchun** [comment]
https://github.com/antchfx/xpath

Support functions

zhangguanzhang ***@***.***> 于 2023年5月29日周一 下午11:17写道：

**Comment by zhengchun** [comment]
https://github.com/antchfx/xpath/commit/c9362c3b0212535e3d4650f8edb77155afdc592b
