### ISSUE TITLE
i can,t parse scripts from  document , using xpath query

### ISSUE THREAD

**Issue by Crypt00o** [antchfx/htmlquery#68]
i can,t parse scripts from  document , using xpath query
for example :  

document:
```html
<html>
           <head>
                <script src="https://example.com/example1.js"></script>
            </head>
            <body>
                 <script src="https://example.com/example2.js"></script>
             </body>
</html>
```

----
```go 
nodes,_:=html.QueryAll(doc,"//script[@src]")
fmt.Println(nodes)   // will ouput [] empty *html.Node slice
```

**Comment by zhengchun** [comment]
it's weird. It works on my local test. What is your version of `htmlquery`, `xpath`.

**Comment by Crypt00o** [comment]
I'm sorry for the confusion. I've just realized that the issue was internal to my code. When I tested the package itself, it works perfectly. I appreciate your response and support!, Thanks !<3
