### ISSUE TITLE
Any plans on supporting object-oriented style nodes?

### ISSUE THREAD

**Issue by Fawers** [antchfx/htmlquery#8]
As of today, one must write, e.g.,

```go
// let `root` be a *html.Node
htmlquery.SelectAttr(htmlquery.FindOne(root, `.//someelement[@id="some=id"]`), "some-attribute")
```

in order to retrieve the attribute `some-attribute` from an element. However, it would be more natural (IMO) and shorter to write, e.g.,

```go
root.FindOne(`.//someelement[@id="some-id"]`).SelectAttr("some-attribute")
```

I wouldn't mind trying and submitting a PR, as I'm just a Go rookie.

***

Btw, thanks for the great library! :slightly_smiling_face:

**Comment by zhengchun** [comment]
Hello,@Fawers, thanks for your suggestion, but the [html.Node](https://godoc.org/golang.org/x/net/html) is another package type, Go can't extend existing types in another package, like as [.Net extension methods](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods).

**Comment by Fawers** [comment]
I understand. Thought it could be done by defining an "alias" to `html.Node`, but maybe I'm just imagining things?

Thought something in the lines of,

```go
type Node html.Node

func (top *Node) FindOne(expr string) *Node { ... }
```

I'll give it a shot when I have the time!

**Comment by Fawers** [comment]
Mm, seems it would require a lot of tweaking. Guess I'll just import `htmlquery` with a shorter name then. :joy: 
Thanks!
